kind: PersistentVolume
apiVersion: v1
metadata:
  name: traefik-acme
  labels:
    type: local
    app: traefik
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/traefik"

